// Biomarker categories
export const BIOMARKER_CATEGORIES = {
  DIABETES: 'diabetes',
  KIDNEY: 'kidney',
  LIVER: 'liver',
  LIPID: 'lipid',
  THYROID: 'thyroid',
  BLOOD_COUNT: 'blood_count',
  VITAMINS: 'vitamins',
  HORMONES: 'hormones',
  OTHER: 'other',
} as const;

export type BiomarkerCategory = typeof BIOMARKER_CATEGORIES[keyof typeof BIOMARKER_CATEGORIES];

// Common biomarker aliases mapping various lab naming conventions to canonical names
export const BIOMARKER_ALIASES: Record<string, string> = {
  // Diabetes panel
  'fbs': 'fasting_blood_sugar',
  'fasting glucose': 'fasting_blood_sugar',
  'glucose fasting': 'fasting_blood_sugar',
  'blood sugar fasting': 'fasting_blood_sugar',
  'glucose (f)': 'fasting_blood_sugar',
  'hba1c': 'hba1c',
  'hemoglobin a1c': 'hba1c',
  'glycated hemoglobin': 'hba1c',
  'glycosylated hemoglobin': 'hba1c',
  'a1c': 'hba1c',
  
  // Kidney function panel
  'creatinine': 'creatinine',
  'creat': 'creatinine',
  'serum creatinine': 'creatinine',
  'bun': 'blood_urea_nitrogen',
  'blood urea nitrogen': 'blood_urea_nitrogen',
  'urea': 'blood_urea_nitrogen',
  'urea nitrogen': 'blood_urea_nitrogen',
  'egfr': 'egfr',
  'gfr': 'egfr',
  'estimated gfr': 'egfr',
  'uric acid': 'uric_acid',
  'urate': 'uric_acid',
  
  // Liver function panel
  'alt': 'alt',
  'sgpt': 'alt',
  'alanine aminotransferase': 'alt',
  'alat': 'alt',
  'ast': 'ast',
  'sgot': 'ast',
  'aspartate aminotransferase': 'ast',
  'asat': 'ast',
  'alp': 'alkaline_phosphatase',
  'alkaline phosphatase': 'alkaline_phosphatase',
  'alk phos': 'alkaline_phosphatase',
  'total bilirubin': 'total_bilirubin',
  'bilirubin total': 'total_bilirubin',
  'bilirubin': 'total_bilirubin',
  'direct bilirubin': 'direct_bilirubin',
  'bilirubin direct': 'direct_bilirubin',
  'albumin': 'albumin',
  'serum albumin': 'albumin',
  'total protein': 'total_protein',
  'protein total': 'total_protein',
  'ggt': 'ggt',
  'gamma gt': 'ggt',
  'gamma glutamyl transferase': 'ggt',
  
  // Lipid panel
  'total cholesterol': 'total_cholesterol',
  'cholesterol total': 'total_cholesterol',
  'cholesterol': 'total_cholesterol',
  'chol': 'total_cholesterol',
  'ldl': 'ldl_cholesterol',
  'ldl-c': 'ldl_cholesterol',
  'ldl cholesterol': 'ldl_cholesterol',
  'low density lipoprotein': 'ldl_cholesterol',
  'hdl': 'hdl_cholesterol',
  'hdl-c': 'hdl_cholesterol',
  'hdl cholesterol': 'hdl_cholesterol',
  'high density lipoprotein': 'hdl_cholesterol',
  'triglycerides': 'triglycerides',
  'tg': 'triglycerides',
  'trigs': 'triglycerides',
  'vldl': 'vldl_cholesterol',
  'vldl cholesterol': 'vldl_cholesterol',
  'very low density lipoprotein': 'vldl_cholesterol',
  
  // Thyroid panel
  'tsh': 'tsh',
  'thyroid stimulating hormone': 'tsh',
  'thyrotropin': 'tsh',
  't3': 't3',
  'triiodothyronine': 't3',
  'total t3': 't3',
  't4': 't4',
  'thyroxine': 't4',
  'total t4': 't4',
  'free t3': 'free_t3',
  'ft3': 'free_t3',
  'free triiodothyronine': 'free_t3',
  'free t4': 'free_t4',
  'ft4': 'free_t4',
  'free thyroxine': 'free_t4',
  
  // Complete Blood Count (CBC)
  'hemoglobin': 'hemoglobin',
  'hb': 'hemoglobin',
  'hgb': 'hemoglobin',
  'haemoglobin': 'hemoglobin',
  'hematocrit': 'hematocrit',
  'hct': 'hematocrit',
  'haematocrit': 'hematocrit',
  'pcv': 'hematocrit',
  'wbc': 'white_blood_cells',
  'white blood cells': 'white_blood_cells',
  'white blood cell count': 'white_blood_cells',
  'leukocytes': 'white_blood_cells',
  'rbc': 'red_blood_cells',
  'red blood cells': 'red_blood_cells',
  'red blood cell count': 'red_blood_cells',
  'erythrocytes': 'red_blood_cells',
  'platelet': 'platelets',
  'platelets': 'platelets',
  'plt': 'platelets',
  'platelet count': 'platelets',
  'mcv': 'mcv',
  'mean corpuscular volume': 'mcv',
  'mch': 'mch',
  'mean corpuscular hemoglobin': 'mch',
  'mchc': 'mchc',
  'mean corpuscular hemoglobin concentration': 'mchc',
  'rdw': 'rdw',
  'red cell distribution width': 'rdw',
  'mpv': 'mpv',
  'mean platelet volume': 'mpv',
  
  // Inflammation markers
  'esr': 'esr',
  'erythrocyte sedimentation rate': 'esr',
  'sed rate': 'esr',
  'crp': 'crp',
  'c-reactive protein': 'crp',
  'c reactive protein': 'crp',
  
  // Electrolytes
  'sodium': 'sodium',
  'na': 'sodium',
  'serum sodium': 'sodium',
  'potassium': 'potassium',
  'k': 'potassium',
  'serum potassium': 'potassium',
  'chloride': 'chloride',
  'cl': 'chloride',
  'serum chloride': 'chloride',
  'calcium': 'calcium',
  'ca': 'calcium',
  'serum calcium': 'calcium',
  'magnesium': 'magnesium',
  'mg': 'magnesium',
  'serum magnesium': 'magnesium',
  
  // Vitamins
  'vitamin d': 'vitamin_d',
  'vit d': 'vitamin_d',
  '25-oh vitamin d': 'vitamin_d',
  'vitamin b12': 'vitamin_b12',
  'vit b12': 'vitamin_b12',
  'cobalamin': 'vitamin_b12',
  'folate': 'folate',
  'folic acid': 'folate',
  'vitamin b9': 'folate',
};
